### ISSUE TITLE
Quarto?

### ISSUE THREAD

**Issue by zachcp** [ikappaki/basilisp-kernel#4]
Hi @ikappaki ,

I've been loving your basilisp tools and am wondering how difficult it might be to make the kernel accessible to the [Quarto](https://quarto.org) ecosystem. They use [jupyter for execution](https://quarto.org/docs/advanced/jupyter/kernel-execution.html) so in theory it should be possible but the quick/obvious things didn't work so I am wondering if you've tried this before.

Thank you 🙏 ,  
zach cp

**Comment by zachcp** [comment]
This seems to work! 


```yaml
---
title: "basilisptest"
kernelspec:
    name: "basilisp"
    language: "clojure"
    display_name: "basilisp"
---


```{clojure}
(+ 1 1)
```
```
